# Generated by Django 4.1.2 on 2023-04-22 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accueil", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="User", new_name="Userr",),
    ]
