# Generated by Django 4.1.2 on 2023-04-26 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accueil", "0005_alter_message_contenu"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="cv",
            field=models.ManyToManyField(null=True, to="accueil.cv"),
        ),
        migrations.AlterField(
            model_name="message",
            name="session",
            field=models.ManyToManyField(null=True, to="accueil.sessioncv"),
        ),
    ]
