# Generated by Django 4.1.2 on 2023-04-26 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accueil", "0007_alter_message_session"),
    ]

    operations = [
        migrations.RenameModel(old_name="Message", new_name="Messagee",),
    ]
