# Generated by Django 4.1.2 on 2023-04-26 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accueil", "0008_rename_message_messagee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messagee",
            name="session",
            field=models.ManyToManyField(null=True, to="accueil.sessioncv"),
        ),
    ]
