# Generated by Django 4.1.2 on 2023-04-26 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accueil", "0009_alter_messagee_session"),
    ]

    operations = [
        migrations.DeleteModel(name="Messagee",),
    ]
