# Generated by Django 4.1.2 on 2023-04-26 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accueil", "0011_messagee"),
    ]

    operations = [
        migrations.DeleteModel(name="Messagee",),
    ]
