# Generated by Django 4.1.2 on 2023-04-26 23:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accueil", "0012_delete_messagee"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de d'envoi",
                    ),
                ),
                ("contenu", models.CharField(max_length=1000)),
                ("username", models.CharField(max_length=20)),
                ("cv", models.ManyToManyField(null=True, to="accueil.cv")),
                ("session", models.ManyToManyField(null=True, to="accueil.sessioncv")),
            ],
        ),
    ]
