# Generated by Django 4.1.2 on 2023-05-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accueil", "0013_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessioncv",
            name="hashed_id",
            field=models.CharField(default="", max_length=200),
        ),
    ]
