# Generated by Django 4.1.2 on 2023-05-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accueil", "0014_sessioncv_hashed_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="type",
            field=models.CharField(default="text", max_length=10),
        ),
    ]
