# Generated by Django 4.1.2 on 2023-05-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accueil", "0015_message_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="contenu",
            field=models.CharField(default="", max_length=1000),
        ),
    ]
