# Generated by Django 4.1.2 on 2023-07-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accueil", "0016_alter_message_contenu"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="messageFromRh",
            field=models.BooleanField(default=False),
        ),
    ]
